cache:
  paths:
  - node_modules/
lint:
  script:
  - npm run lint
arlas-web-components-doc:
  script:
  - npm install
  - npm run build-release
  artifacts:
    paths:
    - documentation
    name: "arlas-wui-toolkit-doc"
mkdocs:
  script:
  - ./mkDocs.sh

